
import app_config from "@config/app_config";
import setup_type from "./setup_type";

const prefix: string = "QuizParticipation";

const setup: setup_type = {
    prefix,
    permission: ["admin", "super_admin"],

    api_host: app_config.api_host,
    api_version: app_config.api_version,
    api_end_point: "quiz-participations",

    module_name: "quiz-participation",
    store_prefix: "quiz_participation",
    route_prefix: "QuizParticipation",
    route_path: "quiz-participation",

    select_fields: [
        "id",
        "quiz_id",
            "session_token",
            "name",
            "email",
            "phone",
            "organization",
            "answers",
            "obtained_marks",
            "percentage",
            "duration",
            "submit_reason",
            "is_completed",
            "is_passed",
            "started_at",
            "submitted_at",
        "status",
        "slug",
        "created_at",
        'deleted_at'
    ],

    sort_by_cols: [
        "id",
        "quiz_id",
            "session_token",
            "name",
            "email",
            "phone",
            "organization",
            "answers",
            "obtained_marks",
            "percentage",
            "duration",
            "submit_reason",
            "is_completed",
            "is_passed",
            "started_at",
            "submitted_at",
        "status",
        "created_at",
    ],
    table_header_data: [
        "id",
        "quiz_id",
            "session_token",
            "name",
            "email",
            "phone",
            "organization",
            "answers",
            "obtained_marks",
            "percentage",
            "duration",
            "submit_reason",
            "is_completed",
            "is_passed",
            "started_at",
            "submitted_at",
        "status",
        "created_at",
    ],
    table_row_data: [
        "id",
        "quiz_id",
            "session_token",
            "name",
            "email",
            "phone",
            "organization",
            "answers",
            "obtained_marks",
            "percentage",
            "duration",
            "submit_reason",
            "is_completed",
            "is_passed",
            "started_at",
            "submitted_at",
        "status",
        "created_at",
    ],
    quick_view_data: [
        "id",
        "quiz_id",
            "session_token",
            "name",
            "email",
            "phone",
            "organization",
            "answers",
            "obtained_marks",
            "percentage",
            "duration",
            "submit_reason",
            "is_completed",
            "is_passed",
            "started_at",
            "submitted_at",
        "status",
        "created_at",
    ],

    layout_title: prefix + " Management",
    page_title: `${prefix} Management`,

    all_page_title: "All " + prefix,
    details_page_title: "Details " + prefix,
    create_page_title: "Create " + prefix,
    edit_page_title: "Edit " + prefix,
};

export default setup;
